"""Pure, spawn-safe domain contracts for MatteLoop."""

from matteloop.core.errors import AppError, ErrorCode, ValidationError
from matteloop.core.geometry import (
    CropGeometryState,
    FramingPlan,
    InteractionGeometry,
    MediaTransform,
    PixelBounds,
    PointF,
    RectF,
    SizeF,
    TimelineGeometryState,
    alpha_bounds,
    apply_framing,
    apply_source_crop,
    build_crop_geometry,
    build_timeline_geometry,
    solve_proportional_scale,
    union_alpha_bounds,
)
from matteloop.core.specs import (
    CollisionPolicy,
    CropSpec,
    EdgeMode,
    FramingSpec,
    OutputSpec,
    RenderRequest,
    SamplingSpec,
    SegmentationSpec,
)

__all__ = [
    "AppError",
    "CollisionPolicy",
    "CropGeometryState",
    "CropSpec",
    "EdgeMode",
    "ErrorCode",
    "FramingSpec",
    "FramingPlan",
    "InteractionGeometry",
    "MediaTransform",
    "OutputSpec",
    "PixelBounds",
    "PointF",
    "RectF",
    "RenderRequest",
    "SamplingSpec",
    "SegmentationSpec",
    "SizeF",
    "TimelineGeometryState",
    "ValidationError",
    "alpha_bounds",
    "apply_framing",
    "apply_source_crop",
    "build_crop_geometry",
    "build_timeline_geometry",
    "solve_proportional_scale",
    "union_alpha_bounds",
]
